---
title: "Lääkkeiden tilastoja"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(DT)
library(plotly)
pakkaus1<-read_delim(paste0(getwd(),"/Aineisto/pakkaus1.txt"),";")
```
Perustiedot
===================================== 
Row {data-width=650}
-----------------------------------------------------------------------

### Perustietoa

```{r}
#Lasketaan eri lääkepakkausten, vnr- ja atc-luokkien määrä
maarat <- pakkaus1 %>% summarise(pakkauksia = n_distinct(PAKKAUSNRO),
                                 vnrnumeroita = n_distinct(VNRNRO),
                                 atcluokkia = n_distinct(ATCKOODI),
                                 lääkenimiä = n_distinct(LAAKENIMI),
                                 myyntilupanumeroita = n_distinct(MYYNTILUPANRO),
                                 EU_myyntilupanumeroita = n_distinct(EUMYYNTILUPANRO),
                                 haltijoita = n_distinct(HALTIJA),
                                 huumausainelääkkeitä = sum(HUUME == "H",na.rm = T),
                                 liikennevaarallisia = sum(LIIKENNEVAARA))
#####SEuraavaksi osuudet

osuudet <- pakkaus1 %>% summarise(vnr_osuus= round(sum(!is.na(VNRNRO))/sum(!is.na(PAKKAUSNRO))*100,1), 
                                 atc_osuus= round(sum(!is.na(ATCKOODI))/sum(!is.na(PAKKAUSNRO))*100,1),
                                 lääkenimet_osuus = round(sum(!is.na(LAAKENIMI))/sum(!is.na(PAKKAUSNRO))*100,1),
                                 myyntilupanumeroiden_osuus = round(sum(!is.na(MYYNTILUPANRO))/sum(!is.na(PAKKAUSNRO))*100,1),
                                 EU_myyntilupanumeroiden_osuus =                              round(sum(!is.na(EUMYYNTILUPANRO))/sum(!is.na(PAKKAUSNRO))*100,1),
                                 huumausainelääkkeiden_osuus = 
                 round(sum(HUUME == "H",na.rm = T)/sum(!is.na(PAKKAUSNRO))*100,1),
                  liikennevaarallisten_osuus = 
                 round(sum(LIIKENNEVAARA)/sum(!is.na(PAKKAUSNRO))*100,1))

#sitten vuodet
vuodet <- pakkaus1 %>% mutate(vuodet = format(KAUPPAANTULOPVM, format = "%Y")) %>% group_by(vuodet) %>%  summarise(lääkepakkauksia =n(),vnr_numeroita = n_distinct(VNRNRO),atc_luokkia = n_distinct(ATCKOODI),lääkenimiä = n_distinct(LAAKENIMI),
                                 myyntilupanumeroita = n_distinct(MYYNTILUPANRO),
                                 EU_myyntilupanumeroita = n_distinct(EUMYYNTILUPANRO),
                                 haltijoita = n_distinct(HALTIJA),
                                 huumausainelääkkeitä = sum(HUUME == "H",na.rm = T),
                                 liikennevaarallisia = sum(LIIKENNEVAARA) ) 

knitr::kable(maarat)
knitr::kable(osuudet)
knitr::kable(vuodet)

```
Row {data-width=150}
-----------------------------------------------------------------------
### Perustietojen kuvaaja1 
```{r}
m<-gather(maarat,muuttuja,arvo,pakkauksia:liikennevaarallisia,factor_key = T)

ggplot(m,aes(x=muuttuja,y = arvo))+geom_bar(stat="identity")+coord_flip()
```
### Perustietojen kuvaaja2 
```{r}
v <- gather(vuodet,muuttuja,arvo,lääkepakkauksia:liikennevaarallisia,factor_key = T)
ggplot(v,aes(x=vuodet,y = log(arvo),fill = muuttuja))+geom_bar(stat="identity")+coord_flip()
```

ATC-luokat
====================
Row {data-width=350}
-----------------------------------------------------------------------

### Pakkausnumeroita per ATC-koodi

```{r}
pakkaus1$ATCPAA <- substr(pakkaus1$ATCKOODI,1,1)
#pakkausten määrä per atc, vnr-numroita per atc, kauppanimi per atc jne.

atc_hajonnat <- pakkaus1 %>% group_by(ATCKOODI) %>% summarise_at(vars(PAKKAUSNRO),funs(min,max,median,mean))

datatable(atc_hajonnat,options = list(
  pageLength = 25, autoWidth = TRUE,filter = 'top'
))
```

### VNR-koodit ja kauppaantulopvm per ATC-luokka, box-plot

```{r}
atc_vnr <- pakkaus1 %>% group_by(ATCKOODI) %>% summarise(maara = n_distinct(VNRNRO))

ggplot(atc_vnr,aes(x = '', y = log(maara)))+geom_boxplot()+labs(title = "vnr-koodeja per ATC-luokka")

#Ei toimi tähän taulukko. Pitää piirtää lisää
#Tehdään muuttuja vuosi huomoiden
aa<-pakkaus1 %>% group_by(ATCPAA,RESEPTISTATUS) %>% summarise(pakkauksia = n_distinct(PAKKAUSNRO))
  
ggplot(aa,aes(x=ATCPAA,y = pakkauksia,fill = RESEPTISTATUS))+geom_bar(stat="identity")+coord_flip()+labs(title = "Pakkausten määrä reseptistatuksen mukaan ATC-pääluokittain")

```


Mittayksiköt
==================
Row {data-width=350}
-----------------------------------------------------------------------
## Pakkausten mittayksiköt
```{r}
mittayksiköt<-pakkaus1 %>% group_by(YKSIKKO) %>% summarise(minimi = min(KOKO),keskiarvo = mean(KOKO),mediaani = median(KOKO),maksimi = max(KOKO))

ggplot(pakkaus1, aes(x = YKSIKKO,y = log(KOKO)))+geom_boxplot()
```
## Mittayksiköt ATC-luokittain
```{r}
#tähän heatmap

df = data.frame(x = 1:5, y = 1:5, z = 1:5)
plot_ly(df, x = ~x, y = ~y, type = "heatmap")
```


Row {data-width=350}
-----------------------------------------------------------------------
## DDD
```{r}

```



Ennustemallit
=================
